import React, { useState, useEffect } from "react";
import { generateRoadmap } from "../../lib/gemini";
import { Loader2, CheckSquare, Square, Download, RefreshCw, Settings } from "lucide-react";

const RoadmapWindow = ({ context, onSetKey, userProfile }) => {
    const [loading, setLoading] = useState(true);
    const [roadmap, setRoadmap] = useState([]);
    const [error, setError] = useState(null);
    const [completedSteps, setCompletedSteps] = useState({});

    useEffect(() => {
        loadRoadmap();
    }, [context]);

    const loadRoadmap = async () => {
        setLoading(true);
        setError(null);
        try {
            const data = await generateRoadmap(context, userProfile);
            setRoadmap(data.steps || data);
        } catch (err) {
            console.error(err);
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    const toggleStep = (index) => {
        setCompletedSteps(prev => ({
            ...prev,
            [index]: !prev[index]
        }));
    };

    if (loading) {
        return (
            <div className="flex flex-col items-center justify-center py-12 text-zinc-500">
                <Loader2 className="w-10 h-10 animate-spin mb-4 text-blue-500" />
                <p>Drafting your action plan...</p>
            </div>
        );
    }

    if (error || !roadmap.length) { // Assuming 'data' from the instruction refers to 'roadmap' here
        return (
            <div className="text-center py-8">
                <p className="text-red-500 mb-6 font-mono text-sm max-w-md mx-auto">{error || "No data received"}</p>
                <div className="flex flex-wrap items-center justify-center gap-3">
                    <button
                        onClick={loadRoadmap}
                        className="flex items-center gap-2 px-4 py-2 bg-zinc-900 text-zinc-400 border border-zinc-800 hover:border-zinc-700 hover:text-white transition-all font-mono text-xs uppercase tracking-tighter"
                    >
                        <RefreshCw className="w-4 h-4" /> [RETRY_SYNC]
                    </button>
                    <button
                        onClick={onSetKey}
                        className="flex items-center gap-2 px-4 py-2 bg-zinc-900 text-yellow-500/80 border border-yellow-500/20 hover:border-yellow-500/50 hover:text-yellow-400 transition-all font-mono text-xs uppercase tracking-tighter"
                    >
                        <Settings className="w-4 h-4" /> [SET_CUSTOM_KEY]
                    </button>
                </div>
            </div>
        )
    }

    const handleExportMD = () => {
        if (!roadmap.length) return;

        const title = context ? context.split('\n')[0].substring(0, 50) : "AI Action Plan";
        let content = `# AI Action Plan: ${title}\n\n`;
        content += `Generated on: ${new Date().toLocaleDateString()}\n\n`;
        content += `## Modules\n\n`;

        roadmap.forEach((item, index) => {
            const status = completedSteps[index] ? "[x]" : "[ ]";
            content += `${index + 1}. ${status} **${item.step}**\n`;
            if (item.details) content += `   - ${item.details}\n`;
            content += `\n`;
        });

        content += `---\n*Generated by WarriorOS AI Expert*`;

        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `roadmap_${new Date().getTime()}.md`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="max-w-xl mx-auto font-mono">
            <div className="mb-6 flex items-center justify-between px-1">
                <p className="text-[10px] text-zinc-500 uppercase tracking-widest">
                    PROGRESS_ANALYSIS: {Object.values(completedSteps).filter(Boolean).length}/{roadmap.length} MODULES_VERIFIED
                </p>
                <button
                    onClick={handleExportMD}
                    className="flex items-center gap-2 text-[10px] text-zinc-500 hover:text-white transition-colors border border-zinc-800 hover:border-zinc-700 px-2 py-1 bg-black uppercase tracking-tighter"
                    title="DOWNLOAD AS MARKDOWN"
                >
                    <Download className="w-3 h-3" /> [EXPORT_MD]
                </button>
            </div>

            <div className="space-y-3">
                {roadmap.map((item, index) => {
                    const isDone = completedSteps[index];
                    return (
                        <div
                            key={index}
                            onClick={() => toggleStep(index)}
                            className={`
                                group p-5 border transition-all flex items-start gap-5 cursor-pointer select-none
                                ${isDone
                                    ? "bg-black border-white/5 opacity-40"
                                    : "bg-black border-white/10 hover:border-blue-500/50 hover:shadow-[0_0_15px_rgba(59,130,246,0.1)]"
                                }
                            `}
                        >
                            <div className={`mt-1 transition-colors ${isDone ? "text-green-500" : "text-zinc-700 group-hover:text-blue-500"}`}>
                                {isDone ?
                                    <div className="w-5 h-5 border border-green-500 flex items-center justify-center text-[10px] font-bold">X</div> :
                                    <div className="w-5 h-5 border border-zinc-700 flex items-center justify-center"></div>
                                }
                            </div>
                            <div>
                                <h4 className={`font-bold text-sm mb-2 tracking-wide ${isDone ? "line-through text-zinc-600" : "text-white"}`}>
                                    MODULE_{String(index + 1).padStart(2, '0')}: {item.step}
                                </h4>
                                {item.details && (
                                    <p className="text-xs text-zinc-500 leading-relaxed italic">
                                        {item.details}
                                    </p>
                                )}
                            </div>
                        </div>
                    );
                })}
            </div>
        </div>
    );
};

export default RoadmapWindow;
